# Generated by Django 5.0 on 2023-12-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=255)),
                ('team_type', models.CharField(max_length=255)),
                ('team_name', models.CharField(max_length=255)),
                ('team_description', models.CharField(max_length=6000)),
                ('location_type', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('work_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
    ]
