# Generated by Django 5.0 on 2023-12-25 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_applicants_applications'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='allteam',
            table=None,
        ),
    ]
