# Generated by Django 5.0 on 2023-12-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_allteam_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applications',
            new_name='Application',
        ),
        migrations.AlterModelTable(
            name='allteam',
            table='teams',
        ),
    ]
